# Generated by Django 5.2.5 on 2025-08-16 08:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('affiliation', models.TextField()),
                ('history', models.TextField()),
                ('main_title', models.CharField(default='Administration Team', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(max_length=255, upload_to='banner/')),
                ('banner_text1', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_text2', models.CharField(blank=True, max_length=250, null=True)),
                ('banner_text3', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='charity/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('id_proof', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('star', models.CharField(blank=True, choices=[('Aswathi', 'Aswathi'), ('Bharani', 'Bharani'), ('Karthika', 'Karthika'), ('Rohini', 'Rohini'), ('Makayiram', 'Makayiram'), ('Thiruvathira', 'Thiruvathira'), ('Punartham', 'Punartham'), ('Pooyam', 'Pooyam'), ('Aayilyam', 'Aayilyam'), ('Makam', 'Makam'), ('Pooram', 'Pooram'), ('Uthram', 'Uthram'), ('Atham', 'Atham'), ('Chittira', 'Chittira'), ('Chothi', 'Chothi'), ('Vishakam', 'Vishakam'), ('Anizham', 'Anizham'), ('Thiruketta', 'Thiruketta'), ('Moolam', 'Moolam'), ('Pooradam', 'Pooradam'), ('Uthradam', 'Uthradam'), ('Thiruvonam', 'Thiruvonam'), ('Avittam', 'Avittam'), ('Chathayam', 'Chathayam'), ('Pooruruttathi', 'Pooruruttathi'), ('Uthrattathi', 'Uthrattathi'), ('Revathi', 'Revathi')], max_length=50, null=True)),
                ('married_sisters', models.CharField(blank=True, max_length=250, null=True)),
                ('married_brothers', models.CharField(blank=True, max_length=250, null=True)),
                ('no_sisters', models.CharField(blank=True, max_length=250, null=True)),
                ('no_brothers', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_job', models.CharField(blank=True, max_length=250, null=True)),
                ('father_job', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=250, null=True)),
                ('landline_no', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
                ('education', models.CharField(blank=True, max_length=250, null=True)),
                ('income', models.CharField(blank=True, max_length=250, null=True)),
                ('job_city', models.CharField(blank=True, max_length=250, null=True)),
                ('job_department', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.CharField(blank=True, max_length=250, null=True)),
                ('job', models.CharField(blank=True, max_length=250, null=True)),
                ('caste', models.CharField(blank=True, choices=[('Mudaliar', 'Mudaliar'), ('Chetty', 'Chetty'), ('Devanga', 'Devanga'), ('Ezhavas_Thiyas', 'Ezhavas & Thiyas'), ('Thandan', 'Thandan')], max_length=250, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced')], max_length=50, null=True)),
                ('physical_condition', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.CharField(blank=True, max_length=250, null=True)),
                ('complexion', models.CharField(blank=True, max_length=250, null=True)),
                ('height', models.CharField(blank=True, max_length=250, null=True)),
                ('time_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('place_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('dob', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('post', models.CharField(blank=True, max_length=250, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=250, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('house_name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('dosham', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='accounts.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to='accounts.customer')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
